version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Deployment started on `date`
      - echo Syncing S3 Content
      - aws s3 sync ./public/ s3://newlyapp.link
  build:
    commands:
      - echo Invalidating CloudFront Cache
       - aws cloudfront create-invalidation --distribution-id E25DI36X14GEYG --paths "/*"
  post_build:
    commands:
      - echo Deployment completed on `date`